### ISSUE TITLE
Ability to use terraform style variables for SPN auth

### ISSUE THREAD

**Issue by mkilchhofer** [Azure/kubelogin#106]
Hi there 👋

We at @swisspost really like kubelogin. Would it be possible to implement a method to use it during a terraform run and reusing the env variables set for the terraform-provider-azurerm:

> ```console
> $ export ARM_CLIENT_ID="00000000-0000-0000-0000-000000000000"
> $ export ARM_CLIENT_SECRET="00000000-0000-0000-0000-000000000000"
> $ export ARM_SUBSCRIPTION_ID="00000000-0000-0000-0000-000000000000"
> $ export ARM_TENANT_ID="00000000-0000-0000-0000-000000000000"
> ```
> _Source: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret#configuring-the-service-principal-in-terraform_

Are you open for such a feature (PR)?

/xref:
- https://github.com/hashicorp/terraform-provider-kubernetes/issues/1753

**Comment by weinong** [comment]
Hi @mkilchhofer, although I am welcome to any contribution, adding TF specific env var will bloat up the env var supported in kubelogin. There is already a complaint about inconsistent use of env var among other SDK in #80.
Besides, the fix in TF will be more generic and valuable, I think

**Comment by mkilchhofer** [comment]
It's not related to TF itself. Its implemented in the AzureRM provider of TF which I assume is also a Microsoft product like kubelogin ;-)

So what do you suggest? I thought about a toggle like `--use-azurerm-env` which would use different envs for initializing the spn login method.
