### ISSUE TITLE
Using kubelogin with Terraform Helm Provider

### ISSUE THREAD

**Issue by kkizer** [Azure/kubelogin#114]
We would like to use Terraform to provision AKS clusters and use the [Helm provider](https://registry.terraform.io/providers/hashicorp/helm/2.6.0) to install Helm charts in those clusters. All of our AKS clusters have Azure Active Directory (AAD) enabled and local Kubernetes accounts are disabled. 

It looks like the [exec plugins](https://registry.terraform.io/providers/hashicorp/helm/latest/docs#exec-plugins) is how we could use kubelogin. To keep things simple, I am using a [service principal connection with a secret](https://github.com/Azure/kubelogin#spn-login-with-secret). Here's what the Terraform config looks like with the sensitive info redacted. This is based on the [AKS provider docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#attributes-reference):

```hcl
provider "helm" {
  kubernetes {
    host                   = azurerm_kubernetes_cluster.AKSCLUSTER.kube_config.0.host
    cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.AKSCLUSTER.kube_config.0.cluster_ca_certificate)
    client_certificate     = base64decode(azurerm_kubernetes_cluster.AKSCLUSTER.kube_config.0.client_certificate)
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"

      # Note: The AAD server app ID of AKS Managed AAD is always 6dae42f8-4368-4678-94ff-3960e28e3630 in any environments.
      # See https://github.com/Azure/kubelogin#exec-plugin-format
      args    = ["get-token", "--environment", "AzurePublicCloud", "--client-id", "***", "--client-secret", "***", "--tenant-id", "***", "--login", "spn", "--serverid", "6dae42f8-4368-4678-94ff-3960e28e3630"]
      command = "kubelogin"
    }
  }
}
```

AKSCLUSTER is the azurerm_kubernetes_cluster AKS resource in the Terraform configuration that is being created.

The Terraform apply fails with the error:
Error: Kubernetes cluster unreachable: Get "https://azameres01kub11614np01-670918ed.hcp.eastus.azmk8s.io:443/version": getting credentials: exec: executable kubelogin failed with exit code 1

We have confirmed that the Terraform agent where the plan is executing is able to connect to the URL in the error message, so it's not a firewall issue. Can kubelogin be used in this way? Am I misreading how to configure the exec plugins on the Helm provider?

**Comment by weinong** [comment]
i think you have a typo? it should be `--server-id` instead of `--serverid`.

**Comment by kkizer** [comment]
Well, that is embarrassing! That fixed it. Thank you very much for your quick response. Closing the issue.
