### ISSUE TITLE
private cluster with public FQDN

### ISSUE THREAD

**Issue by devon-whil** [Azure/kubelogin#116]
I created a cluster with terraform using the following options:
```
private_cluster_enabled = true
public_network_access_enabled = false
private_cluster_public_fqdn_enabled = true
```
This resulted in a public FQDN that resolves to the private IP of the cluster, which looks like this: `.hcp.westus3.azmk8s.io`
Kubelogin is trying to use the private FQDN, which looks like the following and gives me a no such host error:
`.privatelink.westus3.azmk8s.io`
I have a VPN connection to the vnet, so if I can get past DNS resolution I should be able to get in.
Is there any way to get Kubelogin to use the public FQDN?

**Comment by weinong** [comment]
@devon-whil I'd suggest you open an issue under https://github.com/Azure/AKS/issues as what you are asking is for AKS to return a kubeconfig using `privateFqdn` in the kubeconfig. Once opened there, I can forward the issue to the PM/Dev

**Comment by levimm** [comment]
we already have that feature to return kubeconfig with public fqdn, with an extra cli arg --public-fqdn.

**Comment by devon-whil** [comment]
@levimm You're right, thank you! That solves my problem. Apologies all around for the noise, closing now.
