### ISSUE TITLE
can kubelogin be used to generate the context/cluster/user? or does it just convert existing entries?

### ISSUE THREAD

**Issue by goenning** [Azure/kubelogin#119]
We're using AKS with AAD and the way I used kubelogin was:

- Followed the "Connect" instruction on AKS, which essentially uses the `az aks get-credentials` command which creates the context with the azure auth plugin.
- I then use kubelogin to switch to AZ CLI auth, which works great!

But is there an option to use kubelogin directly and skip the first command? Something like `kubelogin setup --resource-group MyRG --name MyAKSName` which would generate the kube context with kubelogin.

I'm trying to avoid granting `Azure Kubernetes Service Cluster User Role` access to all developers as it's only ever needed for the initial `az aks get-credentials` run, they don't need it after converting to kubelogin.

**Comment by weinong** [comment]
Hi @goenning if you are reconstructing the kubeconfig using kubelogin, don't you also need ca bundle and fqdn? where would they come from? Why not just check in the converted kubeconfig into repo?

**Comment by goenning** [comment]
Yeah, we considered doing that as well. But we found yesterday that Azure Portal Liv logs also require `Azure Kubernetes Service Cluster User Role`, so I guess there's no way to avoid that. But on the other hand, this role doesn't seem to give any special permissions, I initially thought this was a special shared user account, but it's still Azure AD at the end.
