### ISSUE TITLE
Official container image

### ISSUE THREAD

**Issue by danmx** [Azure/kubelogin#13]
An offcial container image would be great. I don't know if `kubelogin` can be used with AKS like `aws-iam-authenticatior` is used with EKS (node authentication) but I know use cases where people use container images for packaging their tooling.

**Comment by weinong** [comment]
Can't you just download the binary in your Dockerfile? After all, it still needs kubectl and everyone has their own preference, no?

**Comment by danmx** [comment]
I could but I would have to manage new versions too 😄

**Comment by weinong** [comment]
closing the issue and will reconsider if there is more demand
