### ISSUE TITLE
Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by Xaseron** [Azure/kubelogin#131]
I'm trying to use kubelogin non-interactively with SPN against a private AKS cluster.
I only get this disappoint error message:
`Unable to connect to the server: EOF`

**Comment by weinong** [comment]
Hi @Xaseron typically I saw this kind of error due to network connectivity issue such as firewall misconfiguration. You can confirm by `curl -k -v` the apiserver fqdn or simply not use AAD/AzureRBAC.

**Comment by Xaseron** [comment]
Yeah it was a firewall problem. But maybe enhance the loggin that is not problem with Azure AD but with the kubeapi server.

**Comment by weinong** [comment]
@Xaseron you can use -v=5 or 7 to see the verbose log. I believe this EOF happened when it is connecting to kube apiserver. This is after kubelogin got the token. So there is no way kubelogin can indicate the firewall issue.
