### ISSUE TITLE
Invalidate token when `az logout`

### ISSUE THREAD

**Issue by antoineozenne** [Azure/kubelogin#137]
The access token in `~/.kube/cache/kubelogin` is valid for 1 hour and is not invalidated when we logout with the command `az logout`. My `kubelogin` command is configured with `--login azurecli`. So, if : 
* I login as a user `A`: `az login -u A`
* I get an access token which is cached in `~/.kube/cache/kubelogin`.
* I logout: `az logout`
* I login as a user `B`: `az login -u B`
* I have the access token of the user A valid for 1 hour, so I have the privileges (because of the groups present in the token) of the user A.

I think this is a critical security issue. Is it possible to invalidate the access token when logout ? Or, at least, remove the access token in cache, but this is not sufficient I think.

**Comment by weinong** [comment]
i think we can [disable token cache](https://github.com/Azure/kubelogin/blob/master/pkg/token/execCredentialPlugin.go#L37) in azurecli mode.

**Comment by weinong** [comment]
fixed in `v0.0.20`
