### ISSUE TITLE
error: unknown shorthand flag: 'l' in -l

### ISSUE THREAD

**Issue by CodyBN** [Azure/kubelogin#139]
When I attempt to use kubelogin convert-kubeconfig -l azurecli I get the error: unknown shorthand flag: 'l' in -l

**Comment by weinong** [comment]
@codyBN, what is your kubelogin version?

**Comment by CodyBN** [comment]
@weinong 

 kubelogin version
kubelogin version  (go1.18.5 windows_amd64)

**Comment by CodyBN** [comment]
@weinong 

I have resolved the issue.

For anyone else that may have this problem. I think at some point I have installed this before through chocolatey and forgot. 
I ran the install again with 
**az aks install-cli**
set paths etc.

To fix this, I deleted the choco install, moved my kubelogin.exe to the same directory as kubectl, cleaned up my environment paths. (Now has the one path to users/{your user}/.azure-kubectl ) 

Re-ran the steps: 
az login
az aks get-credentials --resource-group {your resource group} --name {name}
kubelogin convert-kubeconfig -l azurecli

Everything is working now

**Comment by Reddy1082** [comment]
I am getting the error

 **kubelogin convert-kubeconfig -l azurecli
error: unknown shorthand flag: 'l' in -l**

I have uninstalled kube-login and reinstalled it and ran the command but getting same error

**Comment by arindam0310018** [comment]
Hello @weinong, @CodyBN,

Error Encountered while using kubelogin - `error: unknown shorthand flag: 'l' in -l`

Below is the summary as how I made Kubelogin worked for my AKS Cluster.

1. Installed Kubelogin using choco :- `choco install kubelogin`

2. AKS uses kubelogin plugin for authentication :- `kubelogin convert-kubeconfig -l azurecli`

Below was the error encountered -

`error: unknown shorthand flag: 'l' in -l`

3. Uninstall kubelogin using choco :- `choco uninstall kubelogin -y`

4. Install kubelogin using Azure Github: https://azure.github.io/kubelogin/install.html

`winget install --id=Microsoft.Azure.Kubelogin -e`

5. Validate Version : - `kubelogin --version`

Below is the output -

```
kubelogin version

git hash: v0.2.8/d7f1c16c95cc0a1a3beb056374def7b744a38b3a

Go version: go1.23.7

Build time: 2025-04-25T17:17:57Z

Platform: windows/amd64
```

6. Get AKS Credentials :- `az aks get-credentials --resource-group <Name of the Resource Group> --name <Name of the AKS Cluster> --overwrite-existing`

7. Use kubelogin plugin for authentication :- `kubelogin convert-kubeconfig -l azurecli`

The command executed successfully.

8. Validate :-` kubectl get nodes`

Below Follows the Output :-

NAME                                                      STATUS         ROLES       AGE        VERSION

aks-agentpool-99335204-vmss000000   Ready          <none>     3h7m      v1.31.7

Hope this helps.

Many Thanks

Best regards, Arindam
