### ISSUE TITLE
Error parsing /usr/local/bin/kubelogin ('utf-8' codec can't decode byte 0xa0 in position 24: invalid start byte)

### ISSUE THREAD

**Issue by wshamroukh** [Azure/kubelogin#141]
when running the command `az aks get-credentials -g aks-demo -n waddahaks` i get the following error:

`Error parsing /usr/local/bin/kubelogin ('utf-8' codec can't decode byte 0xa0 in position 24: invalid start byte)
`

and when i run the command `kubectl get pod` i get the following error:

`error: error loading config file "/usr/local/bin/kubelogin": yaml: control characters are not allowed
`

**Comment by weinong** [comment]
what was your command to install `kubelogin`?

**Comment by weinong** [comment]
please reopen with your installation/repro steps
