### ISSUE TITLE
Security Groups are not part of the token

### ISSUE THREAD

**Issue by VF-mbrauer** [Azure/kubelogin#144]
The access token, which comes back does not contain groups
```
"groups": [
   mySG1,
   mySG2,
   .....
]
```
Is that feature missing or does it needs to be queried additionally with another API Permission?
- https://graph.microsoft.com/Directory.Read.All

**Comment by weinong** [comment]
does your token contain [overage claim](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens#groups-overage-claim)? If so, that means you have more than 200 groups. If you are using AKS, it won't be a problem. But if you are using self-managed k8s, you will need to configure api-server with authentication webhook like https://github.com/kubeguard/guard

**Comment by weinong** [comment]
please reopen if it's unclear

**Comment by OneCricketeer** [comment]
@weinong So, there is no way to implement the overage check in kubelogin itself?

**Comment by weinong** [comment]
it's impossible since kubelogin cannot modify the token claims.

**Comment by OneCricketeer** [comment]
@weinong Thanks, but I wasn't proposing to **_modify_** the claims. Rather, to call the Graph API, as the documentation says

> If a user is a member of more groups than the overage limit (150 for SAML tokens, 200 for JWT tokens), the groups claim isn't included in the token. Instead, it includes an overage claim in the token that *indicates to the application to query the Microsoft Graph API to retrieve the user's group membership*

https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#groups-overage-claim

I've not looked through the code yet, but based on the errors we're experiencing with users in 200+ groups, I'm guessing this case isn't handled (and I'm not sure I understand why kubeguard would be required; I think I found a commit message that indicates it does check the overage claim)
