### ISSUE TITLE
Workload identity is not supported anymore

### ISSUE THREAD

**Issue by clry-ida** [Azure/kubelogin#147]
Documentation and examples include "workloadidentity" as a parameter for federated credentials, however, when using this the following error is displayed:

`Error: 'workloadidentity' is not a supported login method. Supported method is one of devicecode,spn,ropc,msi,azurecli`

**Comment by weinong** [comment]
your version may be too old?

**Comment by clry-ida** [comment]
You're correct. I thought I had the newest version.. I didn't.
