### ISSUE TITLE
setup-kubelogin github action

### ISSUE THREAD

**Issue by bonddim** [Azure/kubelogin#164]
Proposal to create github action **Azure/setup-kubelogin**
[Azure/aks-set-context](https://github.com/marketplace/actions/azure-kubernetes-set-context) action has kubelogin as optional dependency.

**Comment by bcho** [comment]
I like this idea, I think we can create a new action with following usage:

```
use: azure/use-kubelogin@v1
with:
  kubelogin-version: v0.0.24
```

**Comment by bonddim** [comment]
@bcho,
Great! Also, it will be good to have possibility to install latest version by default, which, probably, should have a requirement on GITHUB_TOKEN.

**Comment by bcho** [comment]
I created a repo for this action: https://github.com/Azure/use-kubelogin/pull/1 Hopefully I can create a 1.0 version next week.

**Comment by bcho** [comment]
Hey we have published the v1 version of `azure/use-kubelogin` here: https://github.com/marketplace/actions/setup-kubelogin . Please have a try and let's know your feedback! 😄 We will work with the Azure/aks-set-context repo owner team to update the documentation, stay tuned.

**Comment by bcho** [comment]
Close as github action implemented. Please report any issues in the Azure/setup-kubelogin repo :)
