### ISSUE TITLE
windows and WSL Install w/ Docker Desktop Installed Fails

### ISSUE THREAD

**Issue by darthmolen** [Azure/kubelogin#166]
When running az aks install-cli on WSL Ubuntu with docker desktop installed, the intialization fails with the following error:

```
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.25.4/bin/linux/amd64/kubectl"
Connection error while attempting to download client ([Errno 30] Read-only file system: '/usr/local/bin/kubectl')
```

On windows, when running the scripts specified, including the path fix, when done, the system still does not use the new pathing, because docker-desktop bin always shows up first in my path, even when I re-arrange my path variable.

I have to manually go set the path of the powershell session I'm in to ONLY the new .azure folders for it to work.

**Comment by darthmolen** [comment]
For windows, I had to create a ps1 path file to explicitly set my path to the azure kubectl/kubelogin as well as any other utilities I might need (such as helm, etc)

For ubuntu, I had to download the right kubectl / kubelogin to a home directory and add that path via .bashrc

That way it bypassed all the pathing problems where docker desktop was taking over

**Comment by weinong** [comment]
what you observed is a general permission issue on Linux as the copy command to /usr/local/bin was run as non-root user. you can either do `sudo az aks install-cli` or specify `--install-location`. I will suggest AKS PM to update the doc if necessary

**Comment by weinong** [comment]
https://learn.microsoft.com/en-us/azure/aks/managed-aad#prerequisites
