### ISSUE TITLE
Provide apt-get and/or snap package

### ISSUE THREAD

**Issue by PeterBindels-TomTom** [Azure/kubelogin#167]
This also makes the package auto-discoverable on Linux command line as the default shell will suggest apt and snap packages containing a command that you tried to run.

**Comment by Exodus** [comment]
I have created: https://snapcraft.io/exodus-kubelogin, which builds from source for all platforms and makes it available under snap, though I have only recently applied for the `kubectl` alias.

Would any of the devs work with me to maintain/adopt the snap? I can help maintain the snap.
cc: @weinong 

I can make a PR to this repo if it needs to live in this repo.

Source is available at:

https://github.com/Exodus/exodus-kubelogin

**Comment by weinong** [comment]
@Exodus awesome! can you please submit a PR in this repo?

**Comment by weinong** [comment]
btw, I created a snap account last December. Just didn't have time to actually implement it :D

**Comment by Exodus** [comment]
The kubelogin package is now available in snap as `kubelogin`.

@weinong I have invited you to admin that snap as well, this can help us set up the automated builds in the Build tab of the snap. Please do so as my user is not part of the Ms organization and am unable to.

**Comment by weinong** [comment]
thanks @Exodus, but it turns out I don't have permissions over Azure org. Requesting...
