### ISSUE TITLE
Missing version information of the binary.

### ISSUE THREAD

**Issue by szymonos** [Azure/kubelogin#188]
There is no version information when running command `kubelogin --version`. Returned result:

``` text
kubelogin version 
git hash: master/b46c5fe18e6f295173c5062b7f30ad623844faef
Go version: go1.19.5
Build time: 2023-02-08T00:52:24Z
Platform: linux/amd64
```

In previous releases there was information about kubelogin version in the 1st line.
I have a script that automatically updates version based on the latest release in GitHub repository and right now it basically downloads it every time, because I cannot determine the currently installed version.

**Comment by Tatsinnit** [comment]
Thank you so much for reporting this, @szymonos, really appreciate it. It is fixed under following PR with details as to what was happening #189 ❤️❤️🙏

Thank you and cc: @weinong + @peterbom

**Comment by szymonos** [comment]
Thank you for the fast response :D. Works perfectly now :). Yep, it was second line ;),
