### ISSUE TITLE
az aks install-cli is broken with 0.0.26

### ISSUE THREAD

**Issue by philthynz** [Azure/kubelogin#191]
The new version seems to be missing some assets, which breaks `az aks install-cli`

```
The detected arch is x86_64, would be treated as amd64, which may not match the actual situation due to translation and other reasons. If there is any problem, please download the appropriate binary by yourself.
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl"
Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.
The detected arch is x86_64, would be treated as amd64, which may not match the actual situation due to translation and other reasons. If there is any problem, please download the appropriate binary by yourself.
Downloading client to "/tmp/tmp719hdx74/kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/v0.0.26/kubelogin.zip"
Connection error while attempting to download client (HTTP Error 404: Not Found)
```

**Comment by philthynz** [comment]
Using `--kubelogin-version 0.0.25` works for now

**Comment by trentmillar** [comment]
My CI/CD is also dependant on this binary and my build just broke.

I have seen this before, this repo's release process is a bit sketchy...the tagged/release is published before the build is complete. So if this build process breaks the .zip/binary never gets added to the release as a package.

**Comment by trentmillar** [comment]
Hi @weinong, In your release job, can you move this step after the build step?

https://github.com/Azure/kubelogin/blob/584497114d74eca24f55f078befb11d8955bb0ba/.github/workflows/release.yml#L37-L46

This way the release isn't created if the other steps fail.

**Comment by Tatsinnit** [comment]
☕️💡thank you for this - to add context -  I think It’s because the release failed on publish due to OpenSSL issue, we can quickly release so that the assets will start appearing again: (below you can see the assets kot there because of the second link withi shows the OpenSSL connection error on publish) 

- https://github.com/Azure/kubelogin/releases/tag/v0.0.26 
- https://github.com/Azure/kubelogin/actions/runs/4129883812/jobs/7135983692
- 
Hope this helps in some context.

**Comment by trentmillar** [comment]
@Tatsinnit  I think you are missing the point. When you publish a release without the built "assets" all projects dependent on this fail. There are GitHub actions in the Marketplace that use kubelogin and these actions fail when using a release that has no binary to download. 

Just like @philthynz our build failed with,
```
WARNING: Downloading client to "/tmp/tmpuenv4e9k/kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/v0.0.26/kubelogin.zip"
ERROR: Connection error while attempting to download client (HTTP Error 404: Not Found)

```

In my case our workflow uses the Azure/CLI Marketplace action which is dependant on/and found your latest release but without the "assets". Just now, I see the release job was successful and the assets are there so thanks! But I bet there are others who had a failed build over the last hour.

All I am saying is maybe don't create your GitHub release until the build is successful which should be a simple change to release.yaml 

**Build -> Create Release -> Add Binaries/Assets** right now you have **Create Release -> Build -> Add Binaries/Assets**

**Comment by Tatsinnit** [comment]
> @Tatsinnit I think you are missing the point. When you publish a release without the built "assets" all projects dependent on this fail. There are GitHub actions in the Marketplace that use kubelogin and these actions fail when using a release that has no binary to download.
> 
> Just like @philthynz our build failed with,
> 
> ```
> WARNING: Downloading client to "/tmp/tmpuenv4e9k/kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/v0.0.26/kubelogin.zip"
> ERROR: Connection error while attempting to download client (HTTP Error 404: Not Found)
> ```
> 
> In my case our workflow uses the Azure/CLI Marketplace action which is dependant on/and found your latest release but without the "assets". Just now, I see the release job was successful and the assets are there so thanks! But I bet there are others who had a failed build over the last hour.
> 
> All I am saying is maybe don't create your GitHub release until the build is successful which should be a simple change to release.yaml
> 
> **Build -> Create Release -> Add Binaries/Assets** right now you have **Create Release -> Build -> Add Binaries/Assets**

Hiya @trentmillar, thanks for the ping and thoughts. ❤️☕️ 🙏 Yep, I am with you, (I think my comment above was mainly towards the original thread of why zip was missing)  and we had similar thinking if you see in a commit here : https://github.com/Azure/kubelogin/commit/14dc89e73c52030ee9bf8358a485f42b20cc709b 

The `publish` needed something called `release_id` as dependency which can only be fed via please, and under #184 we re-arranged the code for the version issue. 

What's next? Thank you so much for the thought and I think I am giving some thought how I will make it more simpler and please tag can be created once publish is done, (will loop back and might add you in that refactor PR?) if that's cool.

Thanks heaps 💡

**Comment by Tatsinnit** [comment]
🔈  General note please: ❤️☕️💡 Thank you for your. patience all release `0.0.26` is out with all 14 artefacts published: **https://github.com/Azure/kubelogin/releases/tag/v0.0.26**

I have done quick test with vanilla cli and vscode as well and both worked hence I believe other consuming tool will behave now.

Some screenshots to back above details:

Also kind and gentle ping to @weinong and @philthynz if this suffices the needs we can close this issue. ☕️💡

<img width="1071" alt="Screenshot 2023-02-09 at 4 42 36 PM" src="https://user-images.githubusercontent.com/6233295/217712587-fdf8e50d-064c-4269-9a0a-78987f8da9a4.png">


<img width="1518" alt="Screenshot 2023-02-09 at 4 30 18 PM" src="https://user-images.githubusercontent.com/6233295/217712510-96b687fe-72bc-400e-8d76-0ac5b04e6342.png">

**Comment by philthynz** [comment]
Works for me. Thanks for the quick fix.

**Comment by trentmillar** [comment]
> 

Thanks @Tatsinnit everything is working great now!

@Tatsinnit sure, I'd be happy to put eyes on this if tagged as a reviewer for your PR 😄

**Comment by weinong** [comment]
the publishing part has always been unreliable, even before @Tatsinnit's change. It makes me question if I should move it to Azure blob storage...
