### ISSUE TITLE
kubelogin.exe failed to run: Access is denied

### ISSUE THREAD

**Issue by iamandymcinnes** [Azure/kubelogin#192]
Hi 

When I try to do a kubelogin after installing the latest, it seemed to work once, then since I just get accessed denied.
I've tried removing my kube config, I've tried deleting and reinstally kubelogin.exe

I'm using latest versions of az cli and azure-kubelogin

This is the error:

```
kubelogin convert-kubeconfig -l azurecli
Program 'kubelogin.exe' failed to run: Access is deniedAt line:1 char:1
+ kubelogin convert-kubeconfig -l azurecli
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ kubelogin convert-kubeconfig -l azurecli
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed```

**Comment by weinong** [comment]
has it worked with you before?

**Comment by weinong** [comment]
how did you install kubelogin? would you mind providing `kubelogin --version`?

**Comment by iamandymcinnes** [comment]
I can't run kubelogin --version as it return the access is denied error.

I installed following the windows details on the github page.

azure-cli                         2.45.0

core                              2.45.0
telemetry                          1.0.8

Extensions:
aks-preview                      0.5.120
azure-devops                      0.25.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

**Comment by Tatsinnit** [comment]
💡 Thank you for this, adding 2 cents worth of idea - just stepping back a little for better understanding. Given you are getting `access denied` for `Kubelogin --version` - its seems the user permission is the issue because you cannot run the tool. Hence a quick build up question: How are you installing this tool (as a first time user)? (Just making sure we got that clear for repro- because I tried both and seems to be behaving fine: are you following one of this approach? https://github.com/Azure/kubelogin#setup ) 

Thanks heaps and cc: @weinong just fyi.

**Comment by iamandymcinnes** [comment]
Hi @Tatsinnit 

Yes I followed the windows instuctions from that link as a first time user :)

Cheers

Andy

**Comment by Tatsinnit** [comment]
Hiya @iamandymcinnes, thank you for sharing, cool, see I tried in completely new machine and seems to be correctly permissioned, I will share how I did it and hopefully it helps.

* I used the right click open `powershell` -- as an administrator.
* Then simpley copy pasted the instruction for windows setup from here: https://github.com/Azure/kubelogin#setup-windows

Here is the successful outcome - 

![image](https://user-images.githubusercontent.com/6233295/217963289-eee9d98f-14d9-45e6-a1d8-1213877c2f9c.png)

I wonder if your user permission is not able to correctly install in local file system. thanks, sorry jsut sharing idea if there is something small which could help.

**Comment by iamandymcinnes** [comment]
Great thanks, I'll try removing it completely, is there any speicifc things I need to delete to ensure I get a clean slate? I've got local admin on my machine and don't usually have any issues with installing things but can double check none of the security things our sec ops are using are interfering.

**Comment by iamandymcinnes** [comment]
I've uninstall az cli completely, deleted the .azure-kubelet and .azure-kubelogin folders from my user directory. 
I then reinstalled the az cli and ran the commands off the install in an admin powershell as recommended:

az aks install-cli
$targetDir="$env:USERPROFILE\.azure-kubelogin"
$oldPath = [System.Environment]::GetEnvironmentVariable("Path","User")
$oldPathArray=($oldPath) -split ";"
if(-Not($oldPathArray -Contains "$targetDir")) {
    write-host "Permanently adding $targetDir to User Path"
    $newPath = "$oldPath;$targetDir" -replace ";+", ";"
    [System.Environment]::SetEnvironmentVariable("Path",$newPath,"User")
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","User"),[System.Environment]::GetEnvironmentVariable("Path","Machine") -join ";"
}

**Comment by iamandymcinnes** [comment]
I've resolved my issue, and thanks for all my help. Turned out it was attack of endpoint for defeneder (aka endpoint for annoying developers) :)
