### ISSUE TITLE
Get AAD token using Client Certificate

### ISSUE THREAD

**Issue by tamilmani1989** [Azure/kubelogin#22]
Kubelogin today supports getting AAD token using client id and client secret. The request here is to get AAD access token using client ID and certificate.

can support this adal api: `adal.NewServicePrincipalTokenFromCertificate`

**Comment by weinong** [comment]
You can try to make the PR. I can help you through the change. 

I'd recommend overload the `-p` option like `az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p ~/mycertfile.pem --tenant contoso.onmicrosoft.com` does and check if -p is a pem file or not.

**Comment by tamilmani1989** [comment]
@weinong i will work on it.. isn't it pfx file?

**Comment by weinong** [comment]
pfx and pem are just containers. in k8s and the rest of cloud native community, using pem is most common

**Comment by weinong** [comment]
```
az login -h

    --password -p            : Credentials like user password, or for a service principal, provide
                               client secret or a pem file with key and public certificate. Will
                               prompt if not given.
```

**Comment by tamilmani1989** [comment]
@weinong let me do similar to this .. is that fine? ihttps://github.com/ccojocar/adal/blob/5ff7a14d7c425e59a5b6019829423861ff47f26e/README.md#client-certificate

**Comment by weinong** [comment]
yep. i can give you pointer to recognize pkcs12 or pem

**Comment by tamilmani1989** [comment]
im testing decoding pkscs12 and it looks like Deocde function of pkcs12 package ([link](https://godoc.org/golang.org/x/crypto/pkcs12#Decode) supports only if pfx has one cert and one key but cert generated by integrated authority in az key vault has more than 1 cert. So i wrote a modified decode function to retrieve required cert and key from pfx file and it worked. Looks like other ppl also hit this issue: https://github.com/Azure/azure-sdk-for-go/issues/5412 

code sample:

```
func decodePkcs12(pkcs []byte, password string) (*x509.Certificate, *rsa.PrivateKey, error) {
        blocks, err:= pkcs12.ToPEM(pkcs,password)
        if err != nil {
                return nil, nil, err
        }

        var (
           cert *x509.Certificate
           priv *rsa.PrivateKey
       )

       for _, block := range blocks {
          if block.Type == "CERTIFICATE" {
            if _, ok := block.Headers["localKeyId"]; ok {
              cert, err = x509.ParseCertificate(block.Bytes)
              if err !=  nil {
                  fmt.Printf("Error parsing certificate from pem block:%v\n", err)
                  continue
              }
            }
          } else if block.Type == "PRIVATE KEY" {
              priv, err = x509.ParsePKCS1PrivateKey(block.Bytes)
              if err != nil {
                fmt.Printf("Error parsing private key from pem block: %v\n",err)
              }
            }
        }

    return cert, priv, nil
}
```
