### ISSUE TITLE
'az aks install-cli' broken : "https://github.com/Azure/kubelogin/releases/download/v0.0.28/kubelogin.zip" ERROR: Connection error while attempting to download client (HTTP Error 404: Not Found)

### ISSUE THREAD

**Issue by kenzie-rasmussen** [Azure/kubelogin#227]
About 20 minutes ago, our deployment pipelines began failing with this issue:

Downloading client to "/tmp/tmpx050w803/kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/v0.0.28/kubelogin.zip"
ERROR: Connection error while attempting to download client (HTTP Error 404: Not Found)

It looks like the release file got moved to https://github.com/Azure/kubelogin/archive/refs/tags/v0.0.28.zip instead of the previous location at "https://github.com/Azure/kubelogin/releases/download/v0.0.28/kubelogin.zip" and that is causing our workflows to fail.

Currently, we use the recommended install suggestions:

```
curl -L https://aka.ms/InstallAzureCli | bash
az aks install-cli
```

Could this be fixed? Maybe copying the file back into the releases folder? We'd really appreciate it, otherwise, we need to stop using this install script and start installing these tools manually. Also, is there a way to specify a version when using the install script?

**Comment by bcho** [comment]
Thanks for reporting, we will track in this issue: #226 226
