### ISSUE TITLE
SPN login not working using 0.0.4

### ISSUE THREAD

**Issue by mohankpep** [Azure/kubelogin#23]
Hi,
I have a Azure AD enabled AKS cluster. I am trying non interactive login with a SP that has Cluster User role assigned to it. But when I execute via kubectl I get:

I0723 17:27:13.956018    6753 execCredentialPlugin.go:111] acquire new token
I0723 17:27:15.046242    6763 execCredentialPlugin.go:111] acquire new token
I0723 17:27:15.789685    6774 execCredentialPlugin.go:111] acquire new token
I0723 17:27:16.445092    6784 execCredentialPlugin.go:111] acquire new token
I0723 17:27:17.195349    6795 execCredentialPlugin.go:111] acquire new token
I0723 17:27:17.926715    6805 execCredentialPlugin.go:111] acquire new token
error: You must be logged in to the server (Unauthorized)

But if I use kubelogin get-token I get the token

**Comment by weinong** [comment]
do you use the new managed AAD or v1 AAD? SP is not supported on v1 AAD

**Comment by weinong** [comment]
my understanding based on offline conversation is that AADv1 cluster was used which is not supported as I stated earlier. closing the issue.
