### ISSUE TITLE
consider to include AZURE_CONFIG_DIR in convert-kubeconfig sub-command

### ISSUE THREAD

**Issue by weinong** [Azure/kubelogin#235]
when a user setups the az cli outside the home directory, e.g. in a jenkins env, the azurecli login in kubelogin will not be able to find the appropriate az context until `AZURE_CONFIG_DIR` is set. The idea is to enable `convert-kubeconfig` sub command to take this path and update kubeconfig so that `get-token` sub-command knows where the az context is

**Comment by VijitaLekharaju** [comment]
This will be very useful for us, and probably other customers as well, reducing the overhead for carrying around the az-context to every kubectl command executed per AKS cluster in automation scripts, shared libraries or other CI/CD implementations.

**Comment by weinong** [comment]
doc update is in #270
