### ISSUE TITLE
You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by libinmathew26** [Azure/kubelogin#236]
Hello,

We see an intermittent issue using kubelogin, which says "**Error: You must be logged in to the server (Unauthorized)**". We are using a Jenkins agent node that spins up a container that downloads version 0.0.26 of kubelogin. Issue pops up once in 25 builds. 

>12:56:25  2023-03-10 12:56:21 CRITICAL: Applying Helmsman labels to [ ****** ] release failed with non-zero exit code 1: exit status 1
12:56:25  output: 
12:56:25  --- stdout ---
12:56:25  
12:56:25  --- stderr ---
12:56:25  error: You must be logged in to the server (Unauthorized)
12:56:25  
12:56:25  2023-03-10 12:56:21,523 - 0001:*****- root:helm_utils - execute_helmsman - ERROR - Helm stderr:
12:56:25  2023-03-10 12:56:21,523 - 0001:***** - root:helm_utils - execute_helmsman - ERROR - 
12:56:25  2023-03-10 12:56:21,523 - 0001:***** - root:helm_utils - execute_helmsman - ERROR - helmsman command with ERROR ran in

**Comment by weinong** [comment]
in Jenkins, different workspaces are run under the same `jenkins` user. By default, kubelogin caches the token in `~/.kube/cache/kubelogin`. So workspaces running at the same time will clash and result in what you observe. The mitigation is to specify `--token-cache-dir` with your workspace specific dir when running `kubelogin convert-kubeconfig`. I will create doc to document this later.

**Comment by weinong** [comment]
https://azure.github.io/kubelogin/topics/jenkins.html

**Comment by libinmathew26** [comment]
Thank you for the response Weinong. We use `kubelogin` inside docker container. Each Jenkins pipeline will trigger the docker container to run kubelogin and perform other remaining task. There is no clash with `~/.kube` and `~/.azure` directory.
