### ISSUE TITLE
Separate downloads per platform

### ISSUE THREAD

**Issue by ocdi** [Azure/kubelogin#25]
Related to #24, I use Windows primarily and to solve https://github.com/lensapp/lens/issues/649 kubelogin was the perfect solution. I looked at the releases tab and aside from the source, a single zip is present. I almost glossed over this as a solution because there is no indication that the build artifact contains Windows, Linux and Mac binaries. It would be helpful to indicate it is for all platforms, or separate these into platform specific files.

Thanks!

**Comment by weinong** [comment]
@ocdi would it be helpful if we just add this to the release note?
```
kubelogin.zip contains binaries for Linix, Mac, and Windows
```

**Comment by ocdi** [comment]
@weinong I think that would be helpful, only issue is I think it would be rare that anyone would download more than one platform at a time.

I am assuming the GitHub actions contains a zip action for the assets, just splitting into 3 zips would be great. I might have a crack at editing this and submit a pr if that's be helpful.
