### ISSUE TITLE
You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by libinmathew26** [Azure/kubelogin#271]
[https://github.com/Azure/kubelogin/issues/236](url)
Based on the closed issue#236, we still the issue intermittently. Please help. 

Hello,

We see an intermittent issue using kubelogin, which says "Error: You must be logged in to the server (Unauthorized)". We are using a Jenkins agent node that spins up a container that downloads version 0.0.26 of kubelogin. Issue pops up once in 25 builds.

`12:56:25 2023-03-10 12:56:21 CRITICAL: Applying Helmsman labels to [ ****** ] release failed with non-zero exit code 1: exit status 1
12:56:25 output:
12:56:25 --- stdout ---
12:56:25
12:56:25 --- stderr ---
12:56:25 error: You must be logged in to the server (Unauthorized)
12:56:25
12:56:25 2023-03-10 12:56:21,523 - 0001:- root:helm_utils - execute_helmsman - ERROR - Helm stderr:
12:56:25 2023-03-10 12:56:21,523 - 0001: - root:helm_utils - execute_helmsman - ERROR -
12:56:25 2023-03-10 12:56:21,523 - 0001:***** - root:helm_utils - execute_helmsman - ERROR - helmsman command with ERROR ran in`

We use kubelogin inside docker container. Each Jenkins pipeline will trigger the docker container to run `kubelogin` and perform other remaining task. There is no clash with `~/.kube` and `~/.azure` directory.

**Comment by weinong** [comment]
can you share the rough timestamp and cluster fqdn with me at weinongw at microsoft dot com?

**Comment by weinong** [comment]
please send me the cluster info if you encounter it again.
