### ISSUE TITLE
Why is there a azurecli login method, but no azureps method?

### ISSUE THREAD

**Issue by Jaykul** [Azure/kubelogin#276]
I just feel like I _have_ to ask this question, since I don't see it answered elsewhere!

_Assuming_ that I use the az CLI, the azurecli option is by far the least intrusive authentication option, but although I'm working with Azure all day, I'm usually using Azure PowerShell, and I'm basically always logged in that way, but not always logged in with the az CLI.

**Comment by weinong** [comment]
because there isn't any SDK providing such option. The one we use is https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/azure_cli_credential.go
