### ISSUE TITLE
'Kubelogin' project name collisions

### ISSUE THREAD

**Issue by MnrGreg** [Azure/kubelogin#28]
Packaging as a `krew` plugin would solve #25 and streamline the user experience. There are however some existing generic ODIC `krew` plugins and `Homebrew` repositories using the same name:

https://github.com/int128/kubelogin
https://github.com/Nordstrom/kubelogin

As this project is specific to Azure OIDC authentication, would it not be more appropriate to name as such? For example:
`azure-kubelogin`
`azure-oidc-login`

I would like to help with the `krew` packaging but need direction on naming first.

**Comment by weinong** [comment]
@MnrGreg thanks for helping out! I'd prefer `azure-kubelogin`. Thank you!

**Comment by weinong** [comment]
we just added homebrew support today
```
brew install Azure/kubelogin/kubelogin
```

**Comment by weinong** [comment]
i spent sometime reviewing `krew`. `krew` plugin is an extension of `kubectl` and is invoked using `kubectl [plugin-name]` pattern. I'm not sure if `kubelogin` is good fit or not.

**Comment by weinong** [comment]
closing the issue since it's staled for a long time
