### ISSUE TITLE
BUG: unknown command "convert-kubeconfig" for "kubelogin"

### ISSUE THREAD

**Issue by eyalsofer** [Azure/kubelogin#280]
In the documentation for Azure it says to run :kubelogin convert-kubeconfig -l azurecli 
but when i run this command i get: error: unknown command "convert-kubeconfig" for "kubelogin"
seems like convert-kubeconfig is deprecated.
I'm using latest version: kubelogin version v1.27.0 (go1.20.1 windows_amd64)

This issue is preventing me from configuring kubelogin for AKS, please advise.

**Comment by weinong** [comment]
what does your `kubelogin -h` look like? how did you install it?

**Comment by weinong** [comment]
looks like you downloaded from a completely different repo :D
Can you follow the official doc? https://azure.github.io/kubelogin/install.html

**Comment by eyalsofer** [comment]
cool thanks @weinong!!

wasn't aware there is separated kubelogin for azure
