### ISSUE TITLE
kubelogin not found after installing with winget

### ISSUE THREAD

**Issue by stmax82** [Azure/kubelogin#281]
**I installed kubelogin using winget:**
![image](https://github.com/Azure/kubelogin/assets/6381927/5adb7b60-c6b8-4049-9a8b-be8d587cbdc8)

**Then restarted the shell, but kubelogin isn't found:**
![image](https://github.com/Azure/kubelogin/assets/6381927/b181eaa1-a394-436a-80d8-a9da3055b5ff)

**Checking the added PATH and the real installation location shows that the added PATH entry is missing a few directories at the end:**
![image](https://github.com/Azure/kubelogin/assets/6381927/0c1026fc-ea22-4313-96fa-d33c4f720883)

**Comment by weinong** [comment]
what is your version of winget? this is fixed in https://github.com/microsoft/winget-cli/pull/3002 and is released in https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview

**Comment by stmax82** [comment]
@weinong looks like this could be the problem. I've got winget 1.4 (stable). I've manually adjusted the PATH for now and will update to winget 1.5 / preview. I'm closing this issue since it doesn't appear to be a package problem.
