### ISSUE TITLE
Error converting kubernetes config file for Service Principle login.

### ISSUE THREAD

**Issue by yjaganathan** [Azure/kubelogin#286]
I am running script to load files on application Pod.We have BASH script to connect AKS Cluster using kubelogin after that connect application pod using kubectl exec -it to access application pod and load files.We have more than 40 script running and intermediately we are getting following error randomly.

BASH script login steps:
az login --service-principal -u <AKS_SP_ID>" -p <AKS_SP_SECRET> --tenant <AKS_TENANT>
az account set --subscription <AKS_SUBSCRIPTION>
az aks get-credentials --resource-group <AKS_RESOURCE_GROUP> --name <AKS_RESOURCE_GROUP> 
kubelogin convert-kubeconfig -l spn

Bash script error log:-
Successfully created the log file.
Checking if the Azure CLI is installed.
Checking if the kubelogin plugin is installed.
Including the VM properties file.
Checking if the required variables have been set.
Parsing the password output.
Attempting az session login.
AZ session created.
Setting az subscription.
AZ subscription set.
Checking for kube config file and downloading if needed.
The kube config file already exists.
The current context is: **<AKS Cluster Name>**
Current context is already set properly.
Converting kubernetes config file for Service Principle login.
Error converting kubernetes config file for Service Principle login.

**Comment by weinong** [comment]
`kubelogin convert-kubeconfig -l spn` should have told you what error is. can you share that? the spn login requires client-id and tenant-id. I'm guessing the conversions from this many scripts clobbered and removed these required settings. a potential solution is to save the kubeconfig separately and uniquely like using mktmp

**Comment by weinong** [comment]
please reopen with more detail if issue persists
