### ISSUE TITLE
kubelogin convert-kubeconfig -l spn returns non zero exit code without any error message

### ISSUE THREAD

**Issue by abhisheklearnsjava** [Azure/kubelogin#300]
In one of our environments we are facing intermittent issue with below command
**kubelogin convert-kubeconfig -l spn**
It just returns non zero exit code without giving any error message. So its is not possible to find out what is wrong.
Environment Details:
Kubelogin version: v0.0.30
kubectl version: 1.26.1

Please suggest how can we get error message in return in case of such failure while calling **kubelogin convert-kubeconfig -l spn**.

**Comment by weinong** [comment]
can you add -v=7 or higher?
