### ISSUE TITLE
Bicep experimental kubernetes with azure auth/k8s admin disabled

### ISSUE THREAD

**Issue by tehho** [Azure/kubelogin#304]
How do we fix a token using kubelogin that will work for a sp/user when a cluster does not support k8s admin accounts?

When we create a cluster we disable the basic admin auth and rely on azure rbac/admin group. 
This disables in my understanding `aks.listClusterAdminCredential().kubeconfigs[0].value` and you need to `az aks get-credentials` to get a working context.
We are not able to do this in bicep since we are in the middle of a deployment, my guess is that `base64(string(customKubeConfig))` might work give that you set the customKubeConfig to the correct format.
The only missing peace is how do we define the user token given a `kubelogin get-token`

```bicep
@secure()
param kubeloginToken string

// assume create cluster instead
resource aks 'Microsoft.ContainerService/managedClusters@2023-04-02-preview' existing = {
  name: 'aks'
}

var customKubeConfig = {
  apiVersion: 'v1'
  clusters: [
    {
      cluster: {
        'certificate-authority-data': aks.listClusterAdminCredential().kubeconfigs[0].value
        server: aks.properties.fqdn
      }
      name: aks.name
    }
  ]
  contexts: [
    {
      context: {
        cluster: aks.name
        user: aks.name
      }
      name: aks.name
    }
  ]
  'current-context': aks.name
  kind: 'Config'
  preferences: {}
  users: [
    {
      name: aks.name
        user: {
          token: kubeloginToken
        }
    }
  ]
}
var kubeConfigRaw = string(customKubeConfig)
var kubeConfig = base64(kubeConfigRaw)

import 'kubernetes@1.0.0' with {
  kubeConfig: kubeConfig
  namespace: 'default'
} as k8s


output customKubeConfig object = customKubeConfig
output kubeConfigRaw string = kubeConfigRaw
output kubeConfig string = kubeConfig
```

**Comment by weinong** [comment]
please reopen if you have more questions
