### ISSUE TITLE
Why kubectl in conjunction with kubelogin sends complete string instead of only user (upn)

### ISSUE THREAD

**Issue by VF-mbrauer** [Azure/kubelogin#328]
When using kubelogin with kubectl it always sends the whole string like
```
Error from server (Forbidden): pods is forbidden: User "https://sts.windows.net/{{ tenantid}}/#name@domain.com" cannot list resource "pods" in API group ""
```

When specifying the ClusterRole we would instead just give the Username the complete string.
Is there any solution for that? Otherwise not really usable.

**Comment by VF-mbrauer** [comment]
@weinong Can you please check?

**Comment by weinong** [comment]
is it AKS with AAD? or do you manage the k8s with oidc and AAD?

**Comment by VF-mbrauer** [comment]
k8s with oidc and AAD

**Comment by weinong** [comment]
chatted with @VF-mbrauer over k8s slack (glad you found me!), the format "issuer#upn" is a result of k8s apiserver configuration below.

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server

--oidc-username-prefix | Prefix prepended to username claims to prevent clashes with existing names (such as system: users). For example, the value oidc: will create usernames like oidc:jane.doe. If this flag isn't provided and --oidc-username-claim is a value other than email the prefix defaults to ( Issuer URL )# where ( Issuer URL ) is the value of --oidc-issuer-url. The value - can be used to disable all prefixing.
