### ISSUE TITLE
Kubectl exec plugin support for spn

### ISSUE THREAD

**Issue by jmcshane** [Azure/kubelogin#34]
It doesn't appear that there is a way to configure the kubectl exec plugin when using spn for authentication. Are there updates required for this plugin to work? If this requires testing, I'm definitely willing to help out as I am building automated processes for spn authentication against AKS Managed AAD clusters.

**Comment by weinong** [comment]
does https://github.com/Azure/kubelogin#service-principal-login-flow-non-interactive not work for you?

**Comment by weinong** [comment]
@jmcshane did you have a chance to look at

> does https://github.com/Azure/kubelogin#service-principal-login-flow-non-interactive not work for you?

**Comment by weinong** [comment]
please re-open if above doc doesnt work for you
