### ISSUE TITLE
Subject Name Issuer based Auth for SPN Login Mode for Kubelogin

### ISSUE THREAD

**Issue by ubee77** [Azure/kubelogin#345]
Hi,

Is SNI based auth to AAD SPN supported for SPN mode of login for kubelogin?

We need to use SNI based auth to get the AAD token. What is the recommended way to use this token Kubelogin?

**Comment by weinong** [comment]
it should be. use spn with certificate. [reference](https://github.com/Azure/kubelogin/blob/master/pkg/token/serviceprincipaltokencertificate.go#L31)

**Comment by ubee77** [comment]
Aah, I was thinking we need to specify something additional. Tried this out, this works fine. Thanks [Weinong Wang](https://github.com/weinong). Closing the issue.
