### ISSUE TITLE
Support OIDC request url & token

### ISSUE THREAD

**Issue by stevehipwell** [Azure/kubelogin#353]
I'd like `kubelogin` to support the `ACTIONS_ID_TOKEN_REQUEST_URL` & `ACTIONS_ID_TOKEN_REQUEST_TOKEN` environmental variables to handle OIDC authentication (in the same way that the AzureRM TF provider works).

Currently I create the token just before running Terraform but if there is a long process before `kubelogin` is called (such as creating an AKS cluster) the OIDC token has expired and Terraform fails.
```[tasklist]
### Tasks
```

**Comment by weinong** [comment]
i like the idea!

**Comment by stevehipwell** [comment]
This is starting to cause us a significant number of failures. I'm going to look at wrapping `kubelogin` with a script but having this as native functionality would be desirable.
