### ISSUE TITLE
Kubelogin Managed Service Identity doesn't work with rolebinding

### ISSUE THREAD

**Issue by infa-ssaurabh** [Azure/kubelogin#39]
I have test kubelogin with Managed Service Identity with below scenario:
1. Created ClusterRoleBinding with group as MSI Object ID --> It works as expected
2. Created RoleBinding inside namespace with group as MSI Object ID --> Get below error:
Error from server (Forbidden): pods is forbidden: User "$OBJECT-ID" cannot list resource "pods" in API group "" in the namespace "default".
Role and Rolebinding Manifest:
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-msi-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-msi-rolebinding
subjects:
  - kind: Group
    name: $OBJECT-ID
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-msi-role

Am I doing something wrong or it is current behaviour?

**Comment by weinong** [comment]
in your role binding, you should use `kind: User`

**Comment by infa-ssaurabh** [comment]
Having `kind: User` worked. Closing the issue.
