### ISSUE TITLE
Query Regarding Autorest Library Usage

### ISSUE THREAD

**Issue by thebeanogamer** [Azure/kubelogin#399]
Kubelogin is a really useful tool, so I'm currently working on getting it packaged for Fedora. However as part of this, I'm running into issues around dependancies. Kubelogin uses multiple modules from https://github.com/Azure/go-autorest, and Fedora's approach to packaging Golang is not well suited to `autorest`'s strategy of releasing multiple packages with differing version numbers and tags from the same repo.

Is there any plan to migrate the remaining usage of `go-autorest` to `azure-sdk-for-go` within Kubelogin? If there is, I'll hold off working on packaging until that's complete. Obviously this isn't exactly a trivial migration, so I'm well aware that even if it's planned, it could take a while.

Thanks again for making this great software.

**Comment by weinong** [comment]
can you elaborate on the issue? go-autorest will not go away due to #331

**Comment by weinong** [comment]
closing. we will gradually be phasing out adal, but there will be some scenarios requiring it like i mentioned earlier. please reopen with more info if you want to continue the discussion
