### ISSUE TITLE
Undefined reference to: gccgoRealSyscall, gccgoRealSyscallNoError, reflect.typelinks, reflect.resolveTypeOff, reflect.typelinks (gollvm)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [Azure/kubelogin#40]
Hi.

I caught such bugs:

> $ make
> rm -f bin/linux_amd64/kubelogin
> CGO_ENABLED=0 go build -o bin/linux_amd64/kubelogin -ldflags "-X main.version=v0.0.6/1ee0da905a5b9ce9dceacff7e914b3c3c1e198ea -X main.goVersion=go1.15.2 -X main.buildTime=2020-10-13T09:09:19Z"
> go: downloading k8s.io/client-go v0.17.4
> go: downloading github.com/spf13/cobra v0.0.6
> go: downloading k8s.io/cli-runtime v0.17.4
> go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
> go: downloading k8s.io/apimachinery v0.17.4
> go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.1
> go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
> go: downloading github.com/Azure/go-autorest/tracing v0.6.0
> go: downloading github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
> go: downloading k8s.io/api v0.17.4
> go: downloading github.com/imdario/mergo v0.3.5
> go: downloading k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
> go: downloading golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
> go: downloading github.com/evanphx/json-patch v4.2.0+incompatible
> go: downloading k8s.io/kube-openapi v0.0.0-20191107075043-30be4d16710a
> go: downloading golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
> go: downloading github.com/googleapis/gnostic v0.0.0-20170729233727-0c5108395e2d
> go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
> go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
> # github.com/Azure/kubelogin
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:55: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:30: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:23: error: undefined reference to 'gccgoRealSyscallNoError'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:37: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:44: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:50: error: undefined reference to 'gccgoRealSyscallNoError'
> /home/oceanfish81/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/type_map.go:74: error: undefined reference to 'reflect.typelinks'
> /home/oceanfish81/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/type_map.go:78: error: undefined reference to 'reflect.resolveTypeOff'
> /home/oceanfish81/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/type_map.go:42: error: undefined reference to 'reflect.typelinks'
> make: *** [Makefile:33: kubelogin] Error 2
> 

I am using 

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

and my here is my environment:

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/go_projects/kubelogin/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build215526650=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> 

CC @ianlancetaylor @thanm @cherrymui

**Comment by ianlancetaylor** [comment]
To fix the undefined references to `'gccgoRealSyscall` and the like, they need to update to a newer version of golang.org/x/sys.

It looks like github.com/modern-go/reflect2 added partial gccgo/GoLLVM compatibility in revision ce5cf29be307ab6039519b733b1861dde5f61c40 which is not included in version 1.0.1.  I don't know whether upgrading to a newer version of that package will help or not.

**Comment by advancedwebdeveloper** [comment]
> To fix the undefined references to `'gccgoRealSyscall` and the like, they need to update to a newer version of golang.org/x/sys.

CC @tamilmani1989 @weinong @ocdi @TomGeske
People, please explain the situation.

> 
> It looks like github.com/modern-go/reflect2 added partial gccgo/GoLLVM compatibility in revision >ce5cf29be307ab6039519b733b1861dde5f61c40 which is not included in version 1.0.1. I don't know whether upgrading to a >newer version of that package will help or not.

reflect2 is no more maintained.
it is recommended to get rid of that decency package ASAP.

**Comment by weinong** [comment]
just curious, why do you need to build it yourself?

**Comment by advancedwebdeveloper** [comment]
> just curious, why do you need to build it yourself?

I was searching for bugs (mainly incompatibility issues).
There is no pre-built releases, for gollvm, for Azure SDK.
And to [generate](https://go.googlesource.com/gollvm/#seetheir) some LLVM IR output, from your package.

**Comment by advancedwebdeveloper** [comment]
> To fix the undefined references to `'gccgoRealSyscall` and the like, they need to update to a newer version of golang.org/x/sys.
>
@weinong , would you handle this?

**Comment by weinong** [comment]
can you give it a try?
https://github.com/weinong/kubelogin/tree/go-mod-update

**Comment by advancedwebdeveloper** [comment]
@weinong , here is what i tried.
I cloned your repo - and performed
> $go mo vendor
. All files under ./pkg folder are compiling without any bugs.

However there is an issues with main.go:

$ go run main.go
# command-line-arguments
./main.go:17:25: error: reference to undefined name 'v'
That's an obvious reference into [https://github.com/Azure/kubelogin/blob/master/main.go#L17](https://github.com/Azure/kubelogin/blob/master/main.go#L17) .

I was able to compile version.go file:

> $ go build -i -v -x version.go
> WORK=/tmp/go-build631361133
> mkdir -p $WORK/b001/
> cat >$WORK/b001/importcfg.link << 'EOF' # internal
> packagefile command-line-arguments=/home/oceanfish81/.cache/go-build/4f/4f8808033ef1a3eb8c92be075ff1a6d2bf605934d3823f2f8bae7d6a3b67b26f-d
> EOF
> mkdir -p $WORK/b001/exe/
> cd .
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -o $WORK/b001/exe/a.out "-Wl,-(" -m64 -Wl,--whole-archive /home/oceanfish81/.cache/go-build/4f/4f8808033ef1a3eb8c92be075ff1a6d2bf605934d3823f2f8bae7d6a3b67b26f-d -Wl,--no-whole-archive "-Wl,-)" -Wl,--build-id=0x466c74714e5f5a64464c5752704f386d676964492f636e49556f6b59684142436376756e574e4a536b2f4a76394d416748495f65754c6d757a774b2d6b412f466c74714e5f5a64464c5752704f386d67696449
> /home/oceanfish81/gollvm_dist/tools/buildid -w $WORK/b001/exe/a.out # internal
> mv $WORK/b001/exe/a.out version
> rm -r $WORK/b001/
> 
But that doesn't mean that it is executing:

> $ ./version
> ./version: symbol lookup error: /lib/libgo.so.12git: undefined symbol: main.main

. So if it shouldn't be compilable into executable - then I do not understand why everything went that smooth.

I have modified your [Makefile ](https://github.com/Azure/kubelogin/blob/master/Makefile#L33) : without CGO_ENABLED=0 and with -i -v -x flags added - I am getting [this](https://gist.github.com/advancedwebdeveloper/1c291385b5c18a9a9685c58004a86cff):

But if I would add CGO_ENABLED=0 back to the Makefile - I am getting

> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:55: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:30: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:23: error: undefined reference to 'gccgoRealSyscallNoError'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:37: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:44: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/go/pkg/mod/golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456/unix/gccgo.go:50: error: undefined reference to 'gccgoRealSyscallNoError'
> /home/oceanfish81/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/type_map.go:74: error: undefined reference to 'reflect.typelinks'
> /home/oceanfish81/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/type_map.go:78: error: undefined reference to 'reflect.resolveTypeOff'
> /home/oceanfish81/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/type_map.go:42: error: undefined reference to 'reflect.typelinks'
> make: *** [Makefile:30: kubelogin] Error 2

**Comment by advancedwebdeveloper** [comment]
Consider switching to [go-reflect](https://github.com/goccy/go-reflect)

Please investigate [this ](https://github.com/json-iterator/go/issues/501) - could be of help.
CC @goccy

**Comment by weinong** [comment]
closing staled issue
