### ISSUE TITLE
"parameter 'identityResourceID' cannot be empty" when using default MSI

### ISSUE THREAD

**Issue by adrianwyatt** [Azure/kubelogin#41]
Logging in with type "MSI" (i.e. `-l msi`) later fails with `parameter 'identityResourceID' cannot be empty`. These commands are being run on an Azure VMSS with a system-assigned identity.

Repro commands:
1. `az login --identity`
2. `az account set -s {subscription}`
3. `sudo az aks get-credentials --resource-group {resourceGroup} --name {clusterName} --overwrite-existing`
4. `sudo kubelogin convert-kubeconfig -l msi`
5. `sudo kubectl get nodes`

At this point we are seeing this error consistently when using any kubectl commands that access the cluster.
```
Error: failed to get token: failed to create service principal from managed identity  for token refresh: parameter 'identityResourceID' cannot be empty
```

**Comment by adrianwyatt** [comment]
Perhaps the check of `p.identityResourceID == ""` [here ](https://github.com/Azure/kubelogin/blob/master/pkg/token/msi.go#L47) is improper? That would make it fall through to `NewServicePrincipalTokenFromMSIWithIdentityResourceID`

```
if p.clientID == "" {
		if p.identityResourceID == "" {
			// no identity specified, use whatever IMDS default to
			spt, err = adal.NewServicePrincipalTokenFromMSI(
				msiEndpoint,
				p.resourceID,
				callback)
			if err != nil {
				return emptyToken, fmt.Errorf("failed to create service principal from managed identity for token refresh: %s", err)
			}
		}
```

**Comment by haitch** [comment]
can you paste the kubeconfig? you can trim off the sensitive part

**Comment by haitch** [comment]
@adrianwyatt @weinong  can we close this issue?

**Comment by adrianwyatt** [comment]
Looks good to me - thank you.

Sent from my phone.
________________________________
