### ISSUE TITLE
Allow Access to PoP package when importing kubelogin. 

### ISSUE THREAD

**Issue by JorgeDaboub** [Azure/kubelogin#455]
Within the Arc Connectivity team, we make use of CSP (client-side proxy).

A sender component used to send messages for our scenarios. The code we use for our Pop scenario is the same one as PoP.

We are collaborating with @julienstroheker to maintain only a single instance of this code. And thus would require the ability to access this module from our CSP component.

I had originally opened this PR https://github.com/Azure/kubelogin/pull/447

@bcho following your suggestion I would instead open a new PR to create a package under pkg/ like pkg/pop, then put the required methods in there, but keep the implementation inside of the internal package.

**Comment by bcho** [comment]
SGTM, feel free to start a PR for this

**Comment by julienstroheker** [comment]
@weinong FYI

We discussed about that while back ago when doing the change about pop on guard.

Goal is to have one central point where pop library is maintained.

Also please in the future, whenever there is changes/refactor on code we added (msal & pop) please tag us for reviews.

Thanks.

**Comment by JorgeDaboub** [comment]
Closing. 
https://github.com/Azure/kubelogin/pull/542
https://github.com/Azure/kubelogin/pull/568
