### ISSUE TITLE
Unable to use kubelogin with SPN

### ISSUE THREAD

**Issue by mohanish12** [Azure/kubelogin#46]
Hi,

I create a clusterrolebinding in my cluster for SPN giving it admin role at k8s level.
after that I used kubelogin and ran the below commands
kubectl convert-kubeconfig
set AAD_SERVICE_PRINCIPAL_CLIENT_ID = <>
set AAD_SERVICE_PRINCIPAL_CLIENT_SECRET = <>

after that when I am trying to use
kubectl get nodes
kubectl get pods
its giving below error
error: you must be logged into the server(unauthorized)

please if any guidance what am I doing wrong

**Comment by weinong** [comment]
what do you put in the cluster role binding? SP's client ID or object ID? you need the latter.

**Comment by mohanish12** [comment]
@weinong : I am using the SP object ID in the cluster role binding

**Comment by weinong** [comment]
i think you missed `-l spn`
```
export KUBECONFIG=/path/to/kubeconfig

kubelogin convert-kubeconfig -l spn

export AAD_SERVICE_PRINCIPAL_CLIENT_ID=<spn client id>
export AAD_SERVICE_PRINCIPAL_CLIENT_SECRET=<spn secret>

kubectl get no
```

**Comment by weinong** [comment]
please reopen if issue persists!
