### ISSUE TITLE
Support for AKS cluster created with managed identity

### ISSUE THREAD

**Issue by RosarioVinoth** [Azure/kubelogin#50]
Hi,

Will there be support for AKS cluster created with managed identity (--enable-managed-identity ) instead of service principle ?  in this case <AAD server app ID> doesn't exist.

**Comment by weinong** [comment]
Having Service Principal (SP) or Managed Service Identity (MSI) is orthogonal to AAD feature. The AAD feature configures the cluster to use AAD for authentication whereas SP and MSI determine how the cluster interact with Azure (like when you expose a Kubernetes Load Balancer type service)

**Comment by RosarioVinoth** [comment]
Thanks for the help & support.
