### ISSUE TITLE
README is AKS specific

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/kubelogin#51]
The README has a lot of AKS references but no examples for unmanaged clusters. This is a plugin for all Kubernetes clusters on Azure, not just AKS, README should reflect that.

examples of AKS specific mentions in README:

> If you are using kubeconfig from AKS AADv1 clusters

> To configure the role binding on Azure Kubernetes Service

> myAKSAutomationServicePrincipal

In addition, it would be good to add a generic set up guide that doesn't assume AKS AADv2 doing everything for you, kind of like https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure/README.md but for out-of-tree (how to set kubeconfig context for a new cluster, etc.)

**Comment by weinong** [comment]
@CecileRobertMichon is it sufficient to just update https://github.com/Azure/kubelogin#features with products? e.g.

## Features

- `convert-kubeconfig` command to converts kubeconfig with existing azure auth provider format to exec credential plugin format
- [device code login](<#device-code-flow-(interactive)>), **supported for AKS Legacy AAD, AKS Managed AAD, CAPZ**
- [non-interactive service principal login](<#service-principal-login-flow-(non-interactive)>), **supported for AKS Managed AAD**
- [non-interactive user principal login](<#user-principal-login-flow-(non-interactive)>) using [Resource owner login flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc), **supported for AKS Managed AAD**
- [non-interactive managed service identity login](<#managed-service-identity-(non-interactive)>), **supported for AKS Managed AAD**
- [non-interactive Azure CLI token login (AKS only)](<#azure-cli-token-login-(non-interactive)>), **supported for AKS Managed AAD**
- AAD token will be cached locally for renewal in device code login and user principal login (ropc) flow. By default, it is saved in `~/.kube/cache/kubelogin/`
- addresses <https://github.com/kubernetes/kubernetes/issues/86410> to remove `spn:` prefix in `audience` claim, if necessary. (based on kubeconfig or commandline argument `--legacy`)
