### ISSUE TITLE
Just tried to install from winget, but looks like kubelogin is not properly added on path (or alias is not working as expected) as kubelogin is not available on command line, even after a machine restart.

### ISSUE THREAD

**Issue by cmp0xff** [Azure/kubelogin#513]
Just tried to install from winget, but looks like kubelogin is not properly added on path (or alias is not working as expected) as kubelogin is not available on command line, even after a machine restart.

_Originally posted by @ggirard07 in https://github.com/Azure/kubelogin/issues/90#issuecomment-1520468356_

Hi, this problem still persists with
```ps
winget --version  # v1.8.1911
cmd /c ver  # Microsoft Windows [Version 10.0.19045.4651]
```

**Comment by weinong** [comment]
Hi @cmp0xff can you open an issue on winget's repo and link this?

**Comment by cmp0xff** [comment]
Hi @weinong, thanks for the comment. `winget` has caused me several similar problems that no one else has reported. As I work on an enterprise machine, I do not have full control over it, and therefore cannot find out if there are problems in my environment, or if it is really something worth looking into.

I will close the issue for now.

**Comment by weinong** [comment]
@cmp0xff no problem. I think the winget team would love to hear that feedback!
