### ISSUE TITLE
Support password field for PKCS certificates or PEMS

### ISSUE THREAD

**Issue by pdefreitas** [Azure/kubelogin#55]
Current implementation decodes PKCS12 with empty password, however there are flows where the PFX might be password protected.

https://github.com/Azure/kubelogin/blob/master/pkg/token/serviceprincipaltoken.go#L89

Another thing thing I've noticied is that it should be pretty straight forward to also support PEMs (just like the Azure CLI supports).

https://github.com/Azure/kubelogin/blob/master/pkg/token/serviceprincipaltoken.go#L200

**Comment by weinong** [comment]
ack. Would you be able to contribute the change? Or you can wait for me but it may take several weeks. :)

**Comment by pdefreitas** [comment]
#54 will do it for my use case.

**Comment by weinong** [comment]
nice! closing this issue then
