### ISSUE TITLE
Question regarding use-cases

### ISSUE THREAD

**Issue by dhirschfeld** [Azure/kubelogin#58]
Sorry for opening an issue for a usage question - I'm not sure if there's a better forum? [GitHub Discussions](https://docs.github.com/en/discussions) don't seem to be enabled here.

In any case, if I wanted to connect `kubectl` to our AAD enabled AKS cluster I would (naively?) think to create a manged identity, assign it the [AKS RBAC Writer](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#azure-kubernetes-service-rbac-writer) role and run the pod using that identity (using the [AAD Pod Identity](https://github.com/Azure/aad-pod-identity) project).

Inside the pod I would connect to the Azure CLI:
[`az login --identity`](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-with-a-managed-identity)

...and then use [`az aks get-credentials`](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_get_credentials) to connect `kubectl` to our AKS.

Is there some problem with doing that? Would that not work? If that *does* work then where does `kubelogin` fit into the picture?

**Comment by weinong** [comment]
good call on setting up discussion! I just enabled it!

your scenario would work, if you want to run it within a pod on a cluster. In fact, this scenario would **require** kubelogin, as `kubectl` doesn't support any other login but `device code`. So the steps are:
* run the pod with container image including kubelogin binary and setup aad pod identity and all that
* az login --identity
* az aks get-credentials
* export KUBECONFIG=/path/to/kubeconfig
* kubelogin convert-kubeconfig -l msi

**Comment by dhirschfeld** [comment]
> *as `kubectl` doesn't support any other login but `device code`*

Ah, right - that's the part I wasn't quite getting. Thanks a lot for the info - I'll go ahead and close as answered!
