### ISSUE TITLE
[MSAL Migration] device code flow is not supported in Managed Device in Conditional Access

### ISSUE THREAD

**Issue by weinong** [Azure/kubelogin#62]
The limitation is documented [here](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/require-managed-devices#known-behavior).

The fix is to adopt [auth code grant flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow)

Sample code: https://github.com/Azure/azure-sdk-for-go/blob/master/sdk/azidentity/interactive_browser_credential.go

**Comment by weinong** [comment]
pending on token cache feature in https://github.com/Azure/azure-sdk-for-go/issues/6602

**Comment by weinong** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/58
https://github.com/Azure/azure-sdk-for-go/issues/6602#issuecomment-1030290807

**Comment by weinong** [comment]
https://github.com/Azure/azure-sdk-for-go/issues/16643

**Comment by weinong** [comment]
adapter between ADAL and AzIdentity
https://github.com/jongio/azidext/blob/master/go/azidext/azure_identity_credential_adapter.go

**Comment by aelij** [comment]
The device code flow is much less convenient than interactive browser, so please migrate.

Additionally, [ADAL has been deprecated](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration) and will no longer receive security updates:

> If you choose not to migrate to MSAL before ADAL support ends in December, 2022, you put your app's security at risk.

**Comment by weinong** [comment]
Hi @aelij, yes, completely agree with you. I'm ramping up a new hire on this project. Hopefully we can tackle it soon. Though, I'm curious to learn what "inconvenience" you are referring to?

**Comment by aelij** [comment]
The fact that you have to copy the device code, open the browser, paste it and login, rather than having the browser simply open :)

**Comment by weinong** [comment]
https://github.com/Azure/azure-sdk-for-go/issues/16643

**Comment by fherbert** [comment]
Any update on the progress to migrate kubelogin to MSAL? 

Would changing to MSAL result in the [access_token be included in the _claim_sources member](https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims) when a distrubted claim is returned? 

We can't use kubelogin with anything other than AKS due to this limitation when users have more than 200 groups.

**Comment by weinong** [comment]
@fherbert we have some login modes implemented in msal such as `interactive`. Though, none of this would help you. That being said, I'd recommend configure your AAD app and k8s to use [app roles](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-apps) for authorization instead of using `groups`

**Comment by weinong** [comment]
closing this issue as [web interactive login mode](https://azure.github.io/kubelogin/concepts/login-modes/interactive.html) is compatible with conditional access policy

**Comment by aelij** [comment]
@weinong I think you should keep this open until ADAL is fully removed from the repo (or track in a different issue). The library was deprecated a while ago and presents a security risk.
