### ISSUE TITLE
 139 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper

### ISSUE THREAD

**Issue by MaximilianKaltner** [Azure/kubelogin#65]
I try to use Azure CLI token login (non interactive) from jenkins pipeline to login to AKS with non interactive but got the following error:

```
+ az login --service-principal --username **** --password **** --tenant mytenant -o none
[Pipeline] sh
+ az aks get-credentials --name mycluster -g mykaas
Merged "mycluster" as current context in /root/.kube/config
[Pipeline] sh
+ export 'KUBECONFIG=/root/.kube/config'
[Pipeline] sh
+ kubelogin convert-kubeconfig -l azurecli
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] sh
+ kubectl get pods -n fm-gtv
E0728 10:11:50.667941     139 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper
E0728 10:12:22.668147     139 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper
Unable to connect to the server: context deadline exceeded
```
Who can help? Is there something missing?

**Comment by weinong** [comment]
can you try -v=5 to see where kubectl was stuck? did it happen all the time?

**Comment by MaximilianKaltner** [comment]
Yes, it happens all the time. Same commands from local machine works fine and can connect to kubernetes cluster successfully, but running on jenkins which is also applied on azure brings the error above. Could this be a proxy problem?!

Here is the result with -v=5:

`[Pipeline] sh
+ export 'KUBECONFIG=/root/.kube/config'
[Pipeline] sh
+ kubelogin convert-kubeconfig -l azurecli
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] sh
+ kubectl '-v=5' get pods -n fm-gtv
E0729 05:55:30.825690     154 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper
I0729 05:55:30.825737     154 cached_discovery.go:121] skipped caching discovery info due to Get https://mycluster-k8s-486f9d27.hcp.westeurope.azmk8s.io:443/api?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E0729 05:56:02.826663     154 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper
I0729 05:56:02.826778     154 cached_discovery.go:121] skipped caching discovery info due to Get https://mycluster-k8s-486f9d27.hcp.westeurope.azmk8s.io:443/api?timeout=32s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I0729 05:56:02.826817     154 shortcut.go:89] Error loading discovery information: Get https://mycluster-k8s-486f9d27.hcp.westeurope.azmk8s.io:443/api?timeout=32s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I0729 05:56:34.827310     154 cached_discovery.go:121] skipped caching discovery info due to Get https://mycluster-k8s-486f9d27.hcp.westeurope.azmk8s.io:443/api?timeout=32s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0729 05:56:34.827234     154 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper
E0729 05:57:06.827729     154 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper
I0729 05:57:06.827807     154 cached_discovery.go:121] skipped caching discovery info due to Get https://mycluster-k8s-486f9d27.hcp.westeurope.azmk8s.io:443/api?timeout=32s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0729 05:57:38.828227     154 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper
I0729 05:57:38.828357     154 cached_discovery.go:121] skipped caching discovery info due to Get https://mycluster-k8s-486f9d27.hcp.westeurope.azmk8s.io:443/api?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I0729 05:57:38.828476     154 helpers.go:217] Connection error: Get https://mycluster-k8s-486f9d27.hcp.westeurope.azmk8s.io:443/api?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
F0729 05:57:38.828494     154 helpers.go:114] Unable to connect to the server: context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

The jenkins agent pod is also applied on kubernetes-cluster with two containers where one container (kubectl) executes the kube-commands and has already set its proxy variables.

`pipeline {

    agent {
        kubernetes {
            defaultContainer 'jnlp'
            yaml '''
                kind: Pod
                metadata:
                  annotations:
                    container.apparmor.security.beta.kubernetes.io/jnlp: runtime/default
                    container.apparmor.security.beta.kubernetes.io/kubectl: runtime/default
                spec:
                  containers:
                  - name: jnlp
                    image: 'nexus.mydomain.net/jenkins/inbound-agent:4.7-1\'
                    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
                  - name: kubectl
                    image: nexus.mydomain.net/ventx/terraform-azurecli-kubectl-helm:latest
                    command:
                    - cat
                    tty: true
                    env:
                    - name: HTTPS_PROXY
                      value: "http://10.6.156.132:8080"
                    - name: HTTP_PROXY
                      value: "http://10.6.156.132:8080"
            '''
        }
    }
...`

**Comment by weinong** [comment]
i believe the problem is your HTTPS_PROXY. since api-server TLS certificate is issued by cluster CA, it's not trusted by your proxy. Can you remove the proxy and try?

**Comment by MaximilianKaltner** [comment]
Thanks for your help. I need HTTPS_PROXY, but I added NO_PROXY variable with value ".hcp.westeurope.azmk8s.io" then it works fine!
