### ISSUE TITLE
v0.0.10 returns 404 not found

### ISSUE THREAD

**Issue by edbergavera** [Azure/kubelogin#67]
We encountered an issue today in our build pipeline. The build script installs the `kubectl` as part of `az aks install-cli`. However, the latest version seems to be not available yet at the time of this posting. The following link returns 404.

https://github.com/Azure/kubelogin/releases/download/v0.0.10/kubelogin.zip

**Comment by weinong** [comment]
sorry that it impacted your pipeline. i cut the release only to find out the darwin/arm64 build won't work with go 1.13 so that i had to drop that release. I'm cutting v0.0.10 again shortly

**Comment by weinong** [comment]
it's been released!
