### ISSUE TITLE
Access is denied to move temporary token to desired output location

### ISSUE THREAD

**Issue by jiayanginfor** [Azure/kubelogin#71]
I am using Kubelogin plugin and run command `kubelogin convert-kubeconfig -l azurecli` to refresh aks token. but got the following error:

![image](https://user-images.githubusercontent.com/79306996/132708832-37d9cfd5-f17f-427f-94ba-cad586ea79a4.png)

Any direction on how I can grant the permission or any insight on the issue?

It does successfully refresh the aks token but sometimes the kubectl commands are not working

**Comment by weinong** [comment]
@ITHedgeHog can you describe your environment plz? can you repro this all the time?

**Comment by ITHedgeHog** [comment]
Hi @weinong yes, I'm using KubeLogin on Windows 10 Professional it is ran during the process of using garden.io against an RBAC enabled Azure Kubernetes instance, it is not a constant issue it happens perhaps 4 or 5 times a day.

I have confirmed this happens less frequently when I just run manual kubectl commands which invoke KubeLogin.

**Comment by ITHedgeHog** [comment]
This is the log I get when running it through garden.io

Command "C:\Users\D.Taylor\.garden\tools\kubectl\31792c5c
85bbb074\kubectl.exe --context=oem-deployed
--namespace=oem-production apply --output=json -f -"
failed with code 1:

Error: unable to write to token cache:
C:\Users\D.Taylor/.kube/cache/kubelogin/AzurePublicCloud-
6dae42f8-4368-4678-94ff-3960e28e3630--.json, err: failed
to move temporary token to desired output location. src=C
:\Users\D.Taylor\.kube\cache\kubelogin\token279059143
dst=C:\Users\D.Taylor/.kube/cache/kubelogin/AzurePublicCl
oud-6dae42f8-4368-4678-94ff-3960e28e3630--.json: rename
C:\Users\D.Taylor\.kube\cache\kubelogin\token279059143
C:\Users\D.Taylor/.kube/cache/kubelogin/AzurePublicCloud-
6dae42f8-4368-4678-94ff-3960e28e3630--.json: Access is
denied.
error: error when retrieving current configuration of:
Resource: "apps/v1, Resource=deployments",
GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "api", Namespace: "oem-production"
from server for: "STDIN": Get
"https://oemdeployed-8a663f13.hcp.uksouth.azmk8s.io:443/a
pis/apps/v1/namespaces/oem-production/deployments/api":
getting credentials: exec: executable kubelogin failed
with exit code 1

Error: unable to write to token cache:
C:\Users\D.Taylor/.kube/cache/kubelogin/AzurePublicCloud-
6dae42f8-4368-4678-94ff-3960e28e3630--.json, err: failed
to move temporary token to desired output location. src=C
:\Users\D.Taylor\.kube\cache\kubelogin\token279059143
dst=C:\Users\D.Taylor/.kube/cache/kubelogin/AzurePublicCl
oud-6dae42f8-4368-4678-94ff-3960e28e3630--.json: rename
C:\Users\D.Taylor\.kube\cache\kubelogin\token279059143
C:\Users\D.Taylor/.kube/cache/kubelogin/AzurePublicCloud-
6dae42f8-4368-4678-94ff-3960e28e3630--.json: Access is
denied.
error: error when retrieving current configuration of:
Resource: "apps/v1, Resource=deployments",
GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "api", Namespace: "oem-production"
from server for: "STDIN": Get
"https://oemdeployed-8a663f13.hcp.uksouth.azmk8s.io:443/a
pis/apps/v1/namespaces/oem-production/deployments/api":
getting credentials: exec: executable kubelogin failed
with exit code 1

**Comment by ITHedgeHog** [comment]
This is becoming more and more of an issue for our developers and is happening multiple times per day, I'm happy to explore writing the fix myself (Perhaps retrying the caching?) if it is necessary - I'd just like some direction from one of the authors on how to resolve this.

We use kubelogin as part of Garden.io, so there are concurrent kubectl requests going on as it synchronises bits of our system.

**Comment by weinong** [comment]
Definitely looking for contribution!

**Comment by ITHedgeHog** [comment]
I'm currently testing a fix for this issue, I'm going to run it at work for a few days to check it actually functions correctly.
