### ISSUE TITLE
Build kubelogin for linux/arm64

### ISSUE THREAD

**Issue by Gearheads** [Azure/kubelogin#75]
Helllo:

Would we be able to release this binary for `linux/arm64` architecture?

Currently, I see we only have the following:
- kubelogin-darwin-amd64.zip
- kubelogin-darwin-arm64.zip
- kubelogin-linux-amd64.zip
- kubelogin-win-amd64.zip

My team uses this binary as dependency for another project, and we would like to start supporting ARM64 architecture, such that the following URL resolves:
https://github.com/Azure/kubelogin/releases/download/v${KUBELOGIN_VERSION}/kubelogin-linux-arm64.zip

**Comment by weinong** [comment]
@Gearheads We can certainly do that, and we are open to any contribution as well! You can use #64 as a reference!

**Comment by Gearheads** [comment]
ok great! thank you for the information. I will start looking into it.
