### ISSUE TITLE
Support converting a single cluster in a kubeconfig file

### ISSUE THREAD

**Issue by evenh** [Azure/kubelogin#87]
It would be nice if kubelogin supported converting a single cluster in a kubeconfig file, and let the other cluster configurations be as-is to reduce the blast radius.

**Comment by anmathew** [comment]
Hi @evenh, what is the behavior you're expecting?

- Use `--cluster` to denote the name of the kubeconfig cluster to convert?

**Comment by evenh** [comment]
That's exactly the behaviour I would like to see 👍🏻  Couldn't find that as a supported use case in the code or docs.
