### ISSUE TITLE
Add Installation Instructions for Windows (and everything other than Mac!?!)

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/kubelogin#88]
Why exactly are there only instructions for brew? 

This should be on winget and instructions should be added ASAP. (and az cli should install it automatically)

**Comment by anumsft** [comment]
For Windows, the easiest way probably is to ` az aks install-cli` 
![cli_kubelogin_windows](https://user-images.githubusercontent.com/68245133/169924897-0738fc6a-2176-44b0-8659-04ecb29e26d1.PNG)

Will add this to the readme.

**Comment by JohnGalt1717** [comment]
Not sure why it can't update the path automatically or if not at least prompt to do it for you? All these apps that endlessly require path updates by hand is super anoying.

**Comment by anmathew** [comment]
WinGet doesn't yet support standalone executables: https://github.com/microsoft/winget-cli/issues/182

**Comment by JohnGalt1717** [comment]
That's what installers are for that would also update the path automatically.

**Comment by mpowrie** [comment]
My $0.02 to install kubelogin and add it to the Windows path in one scriptlet:
`az aks install-cli
$targetDir="$env:USERPROFILE\.azure-kubelogin"
$oldPath = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path
$oldPathArray=($env:Path) -split ';'
if(-Not($oldPathArray -Contains "$targetDir")) {
    write-host "Adding $targetDir to Windows paths"
    $newPath = "$oldPath;$targetDir"
    Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH -Value "$newPath"
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
}
write-host "Windows paths:"
($env:Path).Replace(';',"`n")

write-host "Converting existing kubeconfig to kubelogin"
kubelogin convert-kubeconfig -l azurecli`

**Comment by weinong** [comment]
fixed in #194
