### ISSUE TITLE
Why aren't the common SDK environment variable names used?

### ISSUE THREAD

**Issue by tkent** [Azure/kubelogin#89]
The environment variables used here are different than those used by the other MSFT SDKs ([dotnet](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet), [golang](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash), [java](https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-azure-hosted-auth))

All of them use:

- `AZURE_CLIENT_ID`
- `AZURE_TENANT_ID`
- `AZURE_CLIENT_SECRET`
- `AZURE_USERNAME`
- `AZURE_PASSWORD`

Here, you need to define entirely different variables names like `AAD_SERVICE_PRINCIPAL_CLIENT_ID`. Is there a reason for this inconsistency? Having it means that any execution environment that needs to use both `kubelogin` and an azure SDK must re-define the same values under two different names.

**Comment by weinong** [comment]
nope. there is no reason for that! I think it's at best to support both so that we don't regress existing users. Would you consider to contribute the changes?

**Comment by tkent** [comment]
ATM, I don't have time to contribute patches to this project. I've already accounted for this inconsistency in our pipelines, but believe it would save other MSFT customers time as they move over to `kubelogin` from the currently-defaulted and soon-to-be depreciated `az-login` [aks#2728](https://github.com/Azure/AKS/issues/2728).

**Comment by weinong** [comment]
no problem. we will look into this later this month or next month

**Comment by GavBurke** [comment]
> no problem. we will look into this later this month or next month

Bump, it's now beyond "next month" ;)

**Comment by weinong** [comment]
i'm planning to pick it up next week!

**Comment by xi2424-npanjwani** [comment]
When will this get released?

**Comment by weinong** [comment]
ack. I will release it this week.
