### ISSUE TITLE
Version command returns null values

### ISSUE THREAD

**Issue by davidbgonz** [Azure/kubelogin#95]
I noticed that when I run `kubelogin --version` that this is the output:
```
❯ kubelogin --version
kubelogin version 
git hash: 
Go version: 
Build time:
```
I tested this with both 0.13 and 0.14 and I get the same result. What information would be most beneficial for you for debugging?
```
❯ go version
go version go1.18.3 linux/amd64
```

**Comment by weinong** [comment]
how did you install it?

**Comment by davidbgonz** [comment]
I installed it through the Arch AUR. These are the build steps outlined in the PKGBUILD. Just dug into the Makefile for the package, you're good. I need to bring this up with the maintainer of the AUR package. I'm 2 for 2 today with opening my mouth before digging a little deeper lol
