### ISSUE TITLE
Unable to run kubelogin convert-kubeconfig multiple times

### ISSUE THREAD

**Issue by dion-gionet** [Azure/kubelogin#98]
Since the latest([v0.0.14](https://github.com/Azure/kubelogin/releases/tag/v0.0.14)) release, we have been unable to run `kubelogin convert-kubeconfig` multiple times as it gives the error `Error: "spn" is not supported yet`. It works if we use the previous [v0.0.13](https://github.com/Azure/kubelogin/releases/tag/v0.0.13) release.

We run the command for every cluster that we authenticate to through Github Actions. Authenticating to the first cluster works fine but when authenticating to the second cluster, our workflow fails at running `kubelogin convert-kubeconfig -l spn --client-id "client_id" --client-secret "client_secret"`. Running the command without the `-l spn` gives us the error `Error: "devicecode" is not supported yet`

This is what we run :
```
az login --service-principal -u "client_id" -p "client_secret" -t "tenant_id" > /dev/null
az aks get-credentials --resource-group cluster_name --name cluster_name --file ~/.kube/config --subscription subscription_id --overwrite-existing > /dev/null
kubelogin convert-kubeconfig -l spn --client-id "client_id" --client-secret "client_secret"
```

We are running this on Ubuntu Github Actions runners : `Ubuntu 20.04.4 LTS`

**Comment by weinong** [comment]
got it. we can add this back today. However, you can simply use -l azurecli that uses the SP you already logged in.

**Comment by dion-gionet** [comment]
> got it. we can add this back today. However, you can simply use -l azurecli that uses the SP you already logged in.

I see, thanks!

**Comment by weinong** [comment]
@rlee85 what is broken in your scenario?

**Comment by weinong** [comment]
@rlees85 what is broken in your scenario?

**Comment by rlees85** [comment]
```
$ rm ~/.kube -rf
$ az aks get-credentials --name cluster1 --resource-group group --subscription sub && kubelogin convert-kubeconfig
Merged "cluster1" as current context in /home/user/.kube/config
$ kubectl config use-context cluster1
Switched to context "cluster1".
$ kubectl get nodes
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code [removed] to authenticate.
NAME                            STATUS   ROLES   AGE   VERSION
[removed]
$ az aks get-credentials --name cluster2 --resource-group group --subscription sub && kubelogin convert-kubeconfig
Merged "cluster2" as current context in /home/user/.kube/config
Error: "devicecode" is not supported yet
```

**Comment by pearj** [comment]
> got it. we can add this back today. However, you can simply use -l azurecli that uses the SP you already logged in.

I've found that `-l azurecli` doesn't work with aks clusters across multiple tenancies, only one tenancy works then the others say `error: You must be logged in to the server (Unauthorized)`

**Comment by weinong** [comment]
@pearj it's addressed in the latest release
